In [1]:
import numpy as np
import scipy as sc
from scipy import sparse

Id = np.identity(2)
sig_x = np.array([[0,1],[1,0]])

In [2]:
def sigma_xi(i,n):
    M0 = [1]
    M1 = sig_x
    
    for j in range(0,i-1):
        M0 = sparse.kron(M0,Id).toarray()
    
    for k in range(i,n):
        M1 = sparse.kron(M1,Id).toarray()
        
    M = sparse.kron(M0,M1).toarray()
    
    return M

In [3]:
def sum_sigma_xi(n):
    M = sigma_xi(1,n)
    
    for j in range(2,n+1):
        M = M + sigma_xi(j,n)
        
    return M
        
sum_sigma_xi(2)

array([[0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.]])

In [55]:
def n_i(n,i):
    M0 = [1]
    M1 = np.array([[0,0],[0,1]])
    
    for j in range(0,i-1):
        M0 = sparse.kron(M0,Id).toarray()
    
    for k in range(i,n):
        M1 = sparse.kron(M1,Id).toarray()
        
    M = sparse.kron(M0,M1).toarray()
    
    return M


def sum_n(n):
    
    dimension = n**2
    m = np.zeros((dimension,dimension))
    
    for j in range(1,n+1):
        m = m + n_i(n,j)
        
    return m

sum_n(2)


array([[0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 2.]])

In [44]:
C_6 = 1
a = 1

def vdw(n,a,C_6):
    
    dimension = 2**n
    m_vdw = np.zeros((dimension,dimension))
    
    for i in range(1,n+1):
        for k in range(1,i):
            r = a*abs(i-k)
            v = C_6/r**6
            m_ik = v * np.dot(n_i(n,i),n_i(n,k))
            m_vdw = m_vdw + m_ik
            
    return m_vdw

vdw(2,1,1)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [60]:
def rydberg_hamiltonian(n, delta, rabi, C_6, a):
    h_m = ((rabi/2) * sum_sigma_xi(n)) - (delta*sum_n(n)) + vdw(n,a,C_6) 
    
    return h_m
print(sum_n(2))
rydberg_hamiltonian(2,1,1,1,1)

[[0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 2.]]


array([[ 0. ,  0.5,  0.5,  0. ],
       [ 0.5, -1. ,  0. ,  0.5],
       [ 0.5,  0. , -1. ,  0.5],
       [ 0. ,  0.5,  0.5, -1. ]])

In [10]:
3/2**2

0.75

In [11]:
basis_vector = np.array([0,0,0,0,1,0,0,0]).T
b = np.array([np.eye(2)[1]]).T
print(b)


[[0.]
 [1.]]


In [3]:
import numpy as np

def comp_basis_vector_to_qubit_states(basis_vector):
    n = int(np.log2(len(basis_vector)))  # Calculate the number of qubits (n)

    # Convert the basis vector to binary representation
    basis_int = int(np.log2(int(''.join(map(str, reversed(basis_vector))), 4)))
    binary_rep = format(basis_int, f'0{n}b')
    print(binary_rep)

    # Initialize a list to store individual qubit states
    qubit_states = []

    # Split the binary representation into n parts
    for i in range(n):
        qubit_binary = binary_rep[i]  # Get the binary value for the i-th qubit
        qubit_states.append([1 - int(qubit_binary), int(qubit_binary)])  # Convert to 2D state vector

    return qubit_states

basis_vector = [0,0,0,0,1,0,0,0]

comp_basis_vector_to_qubit_states(basis_vector)

1000


[[0, 1], [1, 0], [1, 0]]